### ISSUE TITLE
Serviço do redis insight não está funcionando.

### ISSUE THREAD

**Issue by birouska-py** [nandorsilva/arc-dados#1]
Serviço do redis insight está apontando para a porta interna do serviço errada

**Comment by birouska-py** [comment]
redisinsight:
    image: redislabs/redisinsight  
    container_name: redisinsight
    hostname: redislabs
    ports:
      - "8001:5540"
    depends_on:
     - redis-stack

**Comment by nandorsilva** [comment]
Ajustado, muito obrigado! abs

**Comment by nandorsilva** [comment]
Obrigado por ter validado. Vou fechar a Issues. abs
